### ISSUE TITLE
Please add a license (also for used third party stuff)

### ISSUE THREAD

**Issue by aismann** [paulocoutinhox/axmol-extensions#1]

**Comment by paulocoutinhox** [comment]
Done

**Comment by aismann** [comment]
Maybe adding this information on readme is a gift to the original author too?
https://gist.github.com/stevetranby/6813fbb427fb57a0cc2ed268b8d15ac0
https://gist.github.com/stevetranby/3d69781cdc3306493a880d936928190e
https://gist.github.com/stevetranby/32bf3f27b389e5497750b33edeb8c8cc

**Comment by paulocoutinhox** [comment]
Hi,

This is in the file header of each file:
https://github.com/paulocoutinhox/axmol-extensions/blob/main/Source/scenes/layer-pan-zoom/STCameraManager.h

After, i will clear the files and will put the author info outside the source code, but inside a .md file to let the file clear as possible.
